[workspace]
members = [
    "ch01_02_hello_world",
    "ch02_00_guessing_game_tutorial",
    "ch03_01_variables_and_mutability",
    "ch03_02_data_types",
    "ch03_03_how_functions_work",
    "ch03_04_comments",
    "ch03_05_control_flow",
]